### ISSUE TITLE
Attempt to stage freed work (segfault)

### ISSUE THREAD

**Issue by luke-jr** [luke-jr/bfgminer#151]
Found on @jddebug 's c411351f9fefe917ee9f01498fd350c7af9b592a rig... Segfault:

```
#0  dec_queued (pool=<optimized out>) at miner.c:2798
#1  0x080561a3 in hash_push (work=0xa215cd8) at miner.c:3679
#2  stage_thread (userdata=0xa092e78) at miner.c:3709
#3  0xb770dd4c in start_thread (arg=0xb6407b40) at pthread_create.c:308
#4  0xb75c6ace in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:130
```

```
(gdb) print *work
$2 = {
  data = "x\326g\267x\326g\267\320\\!\n\320\\!\nesult\":{\"data\":\"0000000147bced428a6ae2c056a9cdea3daf526609520c51cc3560790000028a00000000a80f34378ba0f2e791cfd41f", 
  hash1 = "bc5a51d6f8106d54217003d6e385d01efc906f6150628cd81a05db8b00000000", 
  midstate = "0000008", '0' <repeats 25 times>, target = '0' <repeats 32 times>, 
  hash = '0' <repeats 24 times>, "80020000", rolls = 1747069986, output = {828928865}, valid = 807549474, blk = {
    ctx_a = 808464432, ctx_b = 808464432, ctx_c = 808464432, ctx_d = 808464432, ctx_e = 808464432, 
    ctx_f = 808464432, ctx_g = 808464432, ctx_h = 808464432, cty_a = 808464432, cty_b = 808464432, 
    cty_c = 808464432, cty_d = 808464432, cty_e = 808464432, cty_f = 808464432, cty_g = 808464432, 
    cty_h = 808464432, merkle = 808464432, ntime = 808466480, nbits = 808464432, nonce = 808464432, 
    fW0 = 808464432, fW1 = 808464432, fW2 = 808464432, fW3 = 808464432, fW15 = 808464432, fW01r = 808464432, 
    fcty_e = 808464432, fcty_e2 = 808464432, W16 = 808464432, W17 = 808464432, W2 = 808529968, PreVal4 = 573583408, 
    T1 = 1768759852, C1addK5 = 1635021668, D1A = 975332724, W2A = 859267362, W17_2 = 1681011513, 
    PreVal4addT1 = 929314867, T1substate0 = 909456435, PreVal4_2 = 875585844, PreVal0 = 1633903670, 
    PreW18 = 1630615608, PreW19 = 1634089015, PreW31 = 895705652, PreW32 = 862151480, B1addK6 = 1717711157, 
    PreVal0addK7 = 858797616, W16addK16 = 878916193, W17addK17 = 1630692664, zeroA = 825636663, zeroB = 1697986865, 
    oneA = 573317730, twoA = 1735549300, threeA = 975336549, fourA = 1717986850, fiveA = 1717986918, 
    sixA = 1717986918, sevenA = 1717986918}, thr = 0x66666666, thr_id = 1717986918, pool = 0x66666666, tv_staged = {
    tv_sec = 1717986918, tv_usec = 1717986918}, mined = 102, clone = 102, cloned = 102, rolltime = 1717986918, 
  longpoll = 102, stale = 102, mandatory = 102, block = 102, queued = 102, work_restart_id = 102 'f', 
  id = 1717986918, hh = {tbl = 0x30303066, prev = 0x30303030, next = 0x2c7d2230, hh_prev = 0x22646922, 
    hh_next = 0x6c756e3a, key = 0xa007d6c, keylen = 73, hashv = 168761992}, work_difficulty = 1.0000000376535816, 
  tmpl = 0x0, tmpl_refcount = 0x0, dataid = 0, tv_getwork = {tv_sec = 1348635875, tv_usec = 25412}, 
  tv_getwork_reply = {tv_sec = 1348635875, tv_usec = 811865}, tv_cloned = {tv_sec = 0, tv_usec = 0}, 
  tv_work_start = {tv_sec = 0, tv_usec = 0}, tv_work_found = {tv_sec = 0, tv_usec = 0}, getwork_mode = -96 '\240'}
```

**Comment by luke-jr** [comment]
Fixed in 4b75896
