### ISSUE TITLE
JIT crash

### ISSUE THREAD

**Issue by DeathfireD** [luke-jr/bfgminer#370]
I use a program to mine multiple ALT coin currencies. It's called MultiMiner. It periodically (every 15 mins) checks all sha ALT coin's for the most profitable one and starts to mine it. I've been encountering JIT crashes every so often when the MultiMiner disconnects from a pool and reconnects to another to mine the new ALT coins. I reported the error log to the MultiMiner developer and he kindly directed me your way since it appears to be a BFGminer error.

Here is the issue along with error log https://github.com/nwoolls/MultiMiner/issues/40
but just in case the post is removed here's the contents.

 nwoolls: "This is one you'll need to report to the bfgminer team:

MultiMiner.Xgminer.MinerLaunchException: bfgminer is exiting after launching with exit code 1.
Details: 0x778a9f45 : C:\Windows\SysWOW64\ntdll.dll : RtlInitializeExceptionChain
Executable: Miners\bfgminer\bfgminer.exe"

and here is my error log.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
MultiMiner.Xgminer.MinerLaunchException: bfgminer is exiting after launching with exit code 1.

Details: 0x778a9f45 : C:\Windows\SysWOW64\ntdll.dll : RtlInitializeExceptionChain

Executable: Miners\bfgminer\bfgminer.exe
Arguments: -I D --scan noauto -o stratum+tcp://mint.bitminter.com:3333 -u MY_USERNAME -p "" -o stratum+tcp://us-east.multipool.us:3332 -u MY_USERNAME -p x -S erupter:.\COM15 -d erupter@.\COM15 -S erupter:.\COM16 -d erupter@.\COM16 -S erupter:.\COM17 -d erupter@.\COM17 -S erupter:.\COM4 -d erupter@.\COM4 -S erupter:.\COM7 -d erupter@.\COM7 -S erupter:.\COM8 -d erupter@.\COM8 --api-listen --api-port 4028 --api-allow W:127.0.0.1, -T -q
at MultiMiner.Xgminer.Miner.EnsureProcessStarts(Process process, ProcessStartInfo startInfo) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner.Xgminer\Miner.cs:line 381
at MultiMiner.Xgminer.Miner.StartMinerProcess(String arguments, Boolean redirectOutput, Boolean ensureProcessStarts, String reason, Boolean startProcess) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner.Xgminer\Miner.cs:line 272
at MultiMiner.Xgminer.Miner.Launch(String reason) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner.Xgminer\Miner.cs:line 227
at MultiMiner.Engine.MiningEngine.LaunchMinerProcess(MinerConfiguration minerConfiguration, String reason) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 594
at MultiMiner.Engine.MiningEngine.StartMining() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 560
at MultiMiner.Engine.MiningEngine.ApplyMiningStrategy(List`1 coinInformation) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner.Engine\MiningEngine.cs:line 260
at MultiMiner.Win.MainForm.CheckAndApplyMiningStrategy() in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner.Win\MainForm.cs:line 2341
at MultiMiner.Win.MainForm.coinStatsTimer_Tick(Object sender, EventArgs e) in d:\Data\Visual Studio Projects\Personal\MultiMiner\MultiMiner.Win\MainForm.cs:line 2330
at System.Windows.Forms.Timer.OnTick(EventArgs e)
at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.5472 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll

MultiMiner.Win
Assembly Version: 2.3.3.94
Win32 Version: 2.3.3.94

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.Win.exe

System.Drawing
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Windows.Forms
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.5468 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

MultiMiner.Utility
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.Utility.DLL

MultiMiner.CoinChoose.Api
Assembly Version: 2.3.3.94
Win32 Version: 2.3.3.94

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.CoinChoose.Api.DLL

MultiMiner.Coin.Api
Assembly Version: 2.3.3.94
Win32 Version: 2.3.3.94

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.Coin.Api.DLL

MultiMiner.Xgminer.Api
Assembly Version: 2.3.3.94
Win32 Version: 2.3.3.94

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.Xgminer.Api.DLL

MultiMiner.Engine
Assembly Version: 2.3.3.94
Win32 Version: 2.3.3.94

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.Engine.DLL

MultiMiner.Xgminer
Assembly Version: 2.3.3.94
Win32 Version: 2.3.3.94

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.Xgminer.DLL

System.Xml
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.5476 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

System.Core
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.5420 built by: Win7SP1

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll

Accessibility
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Accessibility/2.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

System.Configuration
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.5476 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

l36lyiv-
Assembly Version: 2.3.3.94
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

bpyiaeyt
Assembly Version: 2.3.3.94
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Web.Extensions
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.5458

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Web.Extensions/3.5.0.0__31bf3856ad364e35/System.Web.Extensions.dll

System.Web.Abstractions
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.5420

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Web.Abstractions/3.5.0.0__31bf3856ad364e35/System.Web.Abstractions.dll

System.Web
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.5474 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_64/System.Web/2.0.0.0__b03f5f7f11d50a3a/System.Web.dll

yfaal51k
Assembly Version: 2.3.3.94
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

exj81tgy
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

MultiMiner.CoinWarz.Api
Assembly Version: 2.3.3.94
Win32 Version: 2.3.3.94

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.CoinWarz.Api.DLL

jkkaprav
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

Newtonsoft.Json
Assembly Version: 4.5.0.0
Win32 Version: 5.0.8.16617

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/Newtonsoft.Json.DLL

tllixjmw
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

yotbvi73
Assembly Version: 2.3.3.94
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

q0tfytfh
Assembly Version: 2.3.3.94
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

phijhsod
Assembly Version: 2.3.3.94
Win32 Version: 2.0.50727.5467 (Win7SP1GDR.050727-5400)

CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

MultiMiner.Coinbase.Api
Assembly Version: 2.3.3.94
Win32 Version: 2.3.3.94

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.Coinbase.Api.DLL

Interop.IWshRuntimeLibrary
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/Interop.IWshRuntimeLibrary.DLL

Interop.Shell32
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/Interop.Shell32.DLL

MultiMiner.Stats.Api
Assembly Version: 2.3.3.94
Win32 Version: 2.3.3.94

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.Stats.Api.DLL

MultiMiner.MobileMiner.Api
Assembly Version: 2.3.3.94
Win32 Version: 2.3.3.94

CodeBase: file:///C:/MultiBitcoin/Apps/bitcoin%20minner/MultiMiner-2.3.2/MultiMiner.MobileMiner.Api.DLL

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by luke-jr** [comment]
I don't see anything here to suggest the problem is with BFGMiner... @nwoolls

**Comment by nwoolls** [comment]
How so? It's bfgminer crashing when it is launched. Seen this reported by many others as well.

**Comment by nwoolls** [comment]
Here's an example with EasyMiner + bfgminer: https://forums.butterflylabs.com/easyminer-support/4207-easyminer-bfgminer-error.html

**Comment by luke-jr** [comment]
@nwoolls I don't see any BFGMiner crash report on _this_ bug..

**Comment by nwoolls** [comment]
I'm not sure what you are saying or asking for to be honest. This has nothing to do with my software and everything to do with bfgminer, crash log or no. If you need a crash log I would recommend working with your user for one.

**Comment by DeathfireD** [comment]
Where are the bfgminer log files located?

**Comment by nwoolls** [comment]
If you add --log-file <filename> to the arguments under Settings>Advanced miner settings, bfgminer should create a log file in the MultiMiner\Miners\bfgminer folder.

**Comment by DeathfireD** [comment]
in what input box for arguments? The SHA-2, Scrypt, or Hardware scan?

**Comment by nwoolls** [comment]
Based on the crash log it was when starting a SHA-2 miner so I would put the arguments in there, though it won't hurt in both.

**Comment by DeathfireD** [comment]
When I hit start BFG crashes. Gives off this error "bfgminer is exiting after launching with exit code 1." and does not create an error log.

**Comment by nwoolls** [comment]
What does it say for Details - same as the original post?

**Comment by DeathfireD** [comment]
yes, same thing.

**Comment by nwoolls** [comment]
Go to the Process Log in MultiMiner, copy the arguments using CTRL+C. Go into the Windows command prompt into the MultiMiner\Miners\bfgminer folder and run bfgminer directly with the same arguments. Then past the full output back here.

**Comment by DeathfireD** [comment]
I created a .bat file and put what I copied from the Process Log "bfgminer --log-file -I D --scan noauto -o stratum+tcp://mint.bitminter.com:3333 -u MY_USERNAME -p "" -o stratum+tcp://us-east.multipool.us:3332 -u MY_USERNAME -p x -S erupter:\.\COM15 -d erupter@\.\COM15 -S erupter:\.\COM16 -d erupter@\.\COM16 -S erupter:\.\COM17 -d erupter@\.\COM17 -S erupter:\.\COM4 -d erupter@\.\COM4 -S erupter:\.\COM7 -d erupter@\.\COM7 -S erupter:\.\COM8 -d erupter@\.\COM8 --api-listen --api-port 4028 --api-allow W:127.0.0.1, -T -q"

It created a -I txt file with the contents "Unexpected extra commandline arguments"

**Comment by nwoolls** [comment]
It's --log-file <filename>, you are missing a file name.

**Comment by DeathfireD** [comment]
That works. So basically I have to wait until it crashes again huh? I just changed the profitability check from 15mins to 5. Hopefully the crash happens while I'm in front of the computer.

**Comment by DeathfireD** [comment]
Just a heads up. You guys probably wont see my crash log until the weekend when I'll be home 24/7 just in case the miner crashes. Right now I've only been running MultiMiner/BFGminer when I get home from work for 5-6 hours. So far no crash has happened but then again the last crash happened 10 hours in.

**Comment by DeathfireD** [comment]
Ok I just let it run over night and it crashed sometime while I was asleep. Here's the error log.

[2014-01-11 12:35:56] New best share: 731
 [2014-01-11 12:35:58] Stratum from pool 0 requested work update
 [2014-01-11 12:36:59] Stratum from pool 0 requested work update
 [2014-01-11 12:37:59] Stratum from pool 0 requested work update
 [2014-01-11 12:38:59] Stratum from pool 0 requested work update
 [2014-01-11 12:40:00] Stratum from pool 0 requested work update
 [2014-01-11 12:41:00] Stratum from pool 0 requested work update
 [2014-01-11 12:42:00] Stratum from pool 0 requested work update
 [2014-01-11 12:43:01] Stratum from pool 0 requested work update
 [2014-01-11 12:44:01] Stratum from pool 0 requested work update
 [2014-01-11 12:45:01] Stratum from pool 0 requested work update
 [2014-01-11 12:46:02] Stratum from pool 0 requested work update
 [2014-01-11 12:47:02] Stratum from pool 0 requested work update
 [2014-01-11 12:47:06] Received kill message
 [2014-01-11 12:47:06] BES 1 shutting down
 [2014-01-11 12:47:06] BES 4 shutting down
 [2014-01-11 12:47:06] BES 3 shutting down
 [2014-01-11 12:47:06] BES 0 shutting down
 [2014-01-11 12:47:06] BES 5 shutting down
 [2014-01-11 12:47:06] BES 2 shutting down
 [2014-01-11 12:47:07] Killing BES 0
 [2014-01-11 12:47:07] Killing BES 1
 [2014-01-11 12:47:07] Killing BES 2
 [2014-01-11 12:47:07] Killing BES 3
 [2014-01-11 12:47:07] Killing BES 4
 [2014-01-11 12:47:07] Killing BES 5
 [2014-01-11 12:47:07] 
Summary of runtime statistics:

 [2014-01-11 12:47:07] Started at [2014-01-11 12:02:08]
 [2014-01-11 12:47:07] Pool: stratum+tcp://us-east.multipool.us:3341
 [2014-01-11 12:47:07] Runtime: 0 hrs : 44 mins : 58 secs
 [2014-01-11 12:47:07] Average hashrate: 2015.9 Megahash/s
 [2014-01-11 12:47:07] Solved blocks: 0
 [2014-01-11 12:47:07] Best share difficulty: 731
 [2014-01-11 12:47:07] Share submissions: 306
 [2014-01-11 12:47:07] Accepted shares: 306
 [2014-01-11 12:47:07] Rejected shares: 0 + 0 stale (0.00%)
 [2014-01-11 12:47:07] Accepted difficulty shares: 1224
 [2014-01-11 12:47:07] Rejected difficulty shares: 0
 [2014-01-11 12:47:07] Hardware errors: 4
 [2014-01-11 12:47:07] Network transfer:  55.0 /  37.0 kB  ( 20.4 /  13.7  B/s)
 [2014-01-11 12:47:07] Efficiency (accepted shares \* difficulty / 2 KB): 27.25
 [2014-01-11 12:47:07] Utility (accepted shares / min): 6.82/min

 [2014-01-11 12:47:07] Unable to get work from server occasions: 0
 [2014-01-11 12:47:07] Work items generated locally: 1770
 [2014-01-11 12:47:07] Submitting work remotely delay occasions: 0
 [2014-01-11 12:47:07] New blocks detected on network: 2

 [2014-01-11 12:47:07] Summary of per device statistics:

 [2014-01-11 12:47:07] BES0       | 5s:324.4 avg:335.4 u:363.0 Mh/s | A:67 R:0+0(none) HW:1/.44%
 [2014-01-11 12:47:07] BES1       | 5s:324.1 avg:335.4 u:359.8 Mh/s | A:47 R:0+0(none) HW:0/none
 [2014-01-11 12:47:07] BES2       | 5s:321.9 avg:335.4 u:350.2 Mh/s | A:50 R:0+0(none) HW:0/none
 [2014-01-11 12:47:07] BES3       | 5s:322.8 avg:335.4 u:339.1 Mh/s | A:41 R:0+0(none) HW:1/.47%
 [2014-01-11 12:47:07] BES4       | 5s:323.5 avg:335.4 u:324.8 Mh/s | A:47 R:0+0(none) HW:1/.49%
 [2014-01-11 12:47:07] BES5       | 5s:323.3 avg:335.4 u:363.0 Mh/s | A:54 R:0+0(none) HW:1/.44%
 [2014-01-11 12:47:07]  
Shutdown signal received.
 [2014-01-11 12:47:07] Started bfgminer 3.9.0
 [2014-01-11 12:47:07] Found BES 0 at \.\COM16
 [2014-01-11 12:47:07] Found BES 1 at \.\COM17
 [2014-01-11 12:47:07] Found BES 2 at \.\COM4
 [2014-01-11 12:47:07] Found BES 3 at \.\COM15
 [2014-01-11 12:47:07] Found BES 4 at \.\COM7
0x4662da : C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-3.9.0-tmp/lowlevel.c (239) : in function (bfg_claim_any) 
0x46142e : C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-3.9.0-tmp/lowl-vcom.c (793) : in function (bfg_claim_serial) 
0x471ca1 : C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-3.9.0-tmp/driver-icarus.c (624) : in function (icarus_detect_custom) 
0x474ace : C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-3.9.0-tmp/driver-erupter.c (38) : in function (_erupter_detect_one) 
0x474bf7 : C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-3.9.0-tmp/driver-erupter.c (78) : in function (erupter_detect_one) 
0x46115d : C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-3.9.0-tmp/lowl-vcom.c (694) : in function (vcom_lowl_probe_wrapper) 
0x474c12 : C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-3.9.0-tmp/driver-erupter.c (84) : in function (erupter_lowl_probe) 
0x42606d : C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-3.9.0-tmp/miner.c (10681) : in function (_probe_device_internal) 
0x4261df : C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\bfgminer.exe : /home/luke-jr/Projects/Education/Tonal/BitCoin/bfgminer/make-release-tmp/bfgminer-3.9.0-tmp/miner.c (10715) : in function (probe_device_thread) 
Failed to init bfd from (C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\pthreadGC2.dll)
0x6248671b : C:\MultiMiner\Apps\bitcoin minner\MultiMiner-2.3.2\Miners\bfgminer\pthreadGC2.dll : pthread_create 
Failed to init bfd from (C:\Windows\syswow64\msvcrt.dll)
0x76391287 : C:\Windows\syswow64\msvcrt.dll : itow_s 
Failed to init bfd from (C:\Windows\syswow64\msvcrt.dll)
0x76391328 : C:\Windows\syswow64\msvcrt.dll : endthreadex 
Failed to init bfd from (C:\Windows\syswow64\kernel32.dll)
0x7628336a : C:\Windows\syswow64\kernel32.dll : BaseThreadInitThunk 
Failed to init bfd from (C:\Windows\SysWOW64\ntdll.dll)
0x778a9f72 : C:\Windows\SysWOW64\ntdll.dll : RtlInitializeExceptionChain 
Failed to init bfd from (C:\Windows\SysWOW64\ntdll.dll)
0x778a9f45 : C:\Windows\SysWOW64\ntdll.dll : RtlInitializeExceptionChain

**Comment by DeathfireD** [comment]
@luke-jr any idea how to fix this so I can run the program for longer than 12 hours.

**Comment by luke-jr** [comment]
That crash is only possible at startup...

Looks like memory corruption, which will need a memory debugger, which Windows does not have... :/

**Comment by DeathfireD** [comment]
@luke-jr Is it possible that bfgminer isn't fully cleared from memory due to how fast it's being disconnected and reconnected? If that's the case then maybe @nwoolls can implement a longer rest time between disconnecting and reconnecting to pools when a coin's profitability has changed in MultiMiner.

**Comment by luke-jr** [comment]
That shouldn't crash it.

**Comment by DeathfireD** [comment]
Is there anything I can do to get you the info you need to fix this because it sounds like the only thing I can do right now is turn off the profitability feature in MultiMiner that disconnects and reconnects bfgminer....and that defeats the purpose of me using MultiMiner :(.

**Comment by luke-jr** [comment]
If you can reproduce it quickly, there's a few approaches we could take... Maybe try running the command over and over since it's a startup issue? You can add the -d? option to make BFGMiner quit immediately when it's successful ;)

**Comment by nwoolls** [comment]
@DeathfireD you can already adjust that time within MultiMiner in Settings > Advanced service settings. There's a setting for how often to fetch Coin API info.

**Comment by DeathfireD** [comment]
@luke-jr so I'd just add -d into my long command? Assuming this does cause the JIT error how's that help us exactly? We'd just be getting the same error over and over again in the log.

Like this?

 bfgminer -d --log-file logfile -I D --scan noauto -o stratum+tcp://mint.bitminter.com:3333 -u MY_USERNAME -p "" -o stratum+tcp://us-east.multipool.us:3332 -u MY_USERNAME -p x -S erupter:\.\COM15 -d erupter@\.\COM15 -S erupter:\.\COM16 -d erupter@\.\COM16 -S erupter:\.\COM17 -d erupter@\.\COM17 -S erupter:\.\COM4 -d erupter@\.\COM4 -S erupter:\.\COM7 -d erupter@\.\COM7 -S erupter:\.\COM8 -d erupter@\.\COM8 --api-listen --api-port 4028 --api-allow W:127.0.0.1, -T -q

**Comment by luke-jr** [comment]
No, -d?
Like this:

```
bfgminer -d? --log-file logfile -I D --scan noauto -o stratum+tcp://mint.bitminter.com:3333 -u MY_USERNAME -p "" -o stratum+tcp://us-east.multipool.us:3332 -u MY_USERNAME -p x -S erupter:\.\COM15 -d erupter@\.\COM15 -S erupter:\.\COM16 -d erupter@\.\COM16 -S erupter:\.\COM17 -d erupter@\.\COM17 -S erupter:\.\COM4 -d erupter@\.\COM4 -S erupter:\.\COM7 -d erupter@\.\COM7 -S erupter:\.\COM8 -d erupter@\.\COM8 --api-listen --api-port 4028 --api-allow W:127.0.0.1, -T -q
```

If you can easily reproduce, there are more options that open up. Like testing against stable and older versions ;)

**Comment by DeathfireD** [comment]
Happened again after running that 40 or so times.

**Comment by DeathfireD** [comment]
Don't quote me on this but I think 3.8.0 works. I've been testing it on that and haven't encountered the error. I do notice that sometimes it only finds 5 out of the 6 erupters I have plugged in though.

**Comment by DeathfireD** [comment]
@luke-jr  Ya so It's still not giving off an error in 3.8.0. I jumped back over to 3.9.0 to see if I could get it to error again and it did after 30 or so tries. I'm gonna try having MultiMiner use 3.8.0 over night and see if it errors out like 3.9.0 does.

Again the only weird thing I'm noticing in 3.8.0 is that sometimes it only sees 5 out of the 6 erupters I have. I'm curious if maybe that plays a part in the crash in 3.9.0.

**Comment by luke-jr** [comment]
Can you also test http://luke.dashjr.org/tmp/code/webisect/webisect.php?dobuild=bfgminer ?

**Comment by DeathfireD** [comment]
That version brings a new problem. After 20 or so tries I get a windows error popup asking me if I want to check the internet for a fix or end program. After I end it and run the command again I end up with two results in my log. No error message though. This same thing has happend 3 times for me. 

 [2014-01-12 01:12:09] Started bfgminer 3.9.0
 [2014-01-12 01:12:09] Found BES 0 at \.\COM17
 [2014-01-12 01:12:09] Found BES 1 at \.\COM15
 [2014-01-12 01:12:09] Found BES 2 at \.\COM4
 [2014-01-12 01:12:09] Found BES 3 at \.\COM16
 [2014-01-12 01:12:09] Found BES 4 at \.\COM7
 [2014-01-12 01:12:13] Started bfgminer 3.9.0
 [2014-01-12 01:12:13] Found BES 0 at \.\COM8
 [2014-01-12 01:12:13] Found BES 1 at \.\COM17
 [2014-01-12 01:12:13] Found BES 2 at \.\COM16
 [2014-01-12 01:12:13] Found BES 3 at \.\COM15
 [2014-01-12 01:12:13] Found BES 4 at \.\COM7
 [2014-01-12 01:12:13] Found BES 5 at \.\COM4
 [2014-01-12 01:12:13] Devices detected:
 [2014-01-12 01:12:13]  Device (driver=erupter; procs=1; path=\.\COM8)
 [2014-01-12 01:12:13]  Device (driver=erupter; procs=1; path=\.\COM17)
 [2014-01-12 01:12:13]  Device (driver=erupter; procs=1; path=\.\COM16)
 [2014-01-12 01:12:13]  Device (driver=erupter; procs=1; path=\.\COM15)
 [2014-01-12 01:12:13]  Device (driver=erupter; procs=1; path=\.\COM7)
 [2014-01-12 01:12:13]  CP2102 USB to UART Bridge Controller by Silicon Labs (driver=erupter; procs=1; serial=0001; path=\.\COM4)
6 devices listed

**Comment by luke-jr** [comment]
Please use http://luke.dashjr.org/tmp/code/webisect/webisect.php to identify the origin of the problem(s). Put any session name and follow directions (use "bfgminer-3.8.0" as good and just "bfgminer" as bad). Be sure to IGNORE(skip) any other unrelated troubles/problems. When done, please report the result here.

**Comment by DeathfireD** [comment]
@luke-jr  I cant even run the commands for the first two. My DOS prompt closes right after I do. Should I keep pressing skip and continue testing each version?

**Comment by luke-jr** [comment]
BFGMiner never closes the prompt. Be sure you're running it in a persistent console.

**Comment by DeathfireD** [comment]
@luke-jr I'm trying to run it like I've always done...with a bat file.

**Comment by DeathfireD** [comment]
ok I tried opening a prompt and CDing to the directory and running the command from there. I get the error --log-file unrecognized option...

**Comment by DeathfireD** [comment]
@luke-jr  It's not liking --scan either...

**Comment by luke-jr** [comment]
Change --scan to -S (uppercase)

**Comment by DeathfireD** [comment]
@luke-jr Two issues. 1) when I run the command now using -S I notice in the prompt that it cant find any devices for the first test.
2) I figure maybe the version in this particular test doesnt yet support erupters so when I go to the webpage and click skip, it sends me to a white page and does not let me continue.

As a side note so far 3.8.0 has not crashed while using it with MultiMiner. It's been well over 20 hours too. (cc. @nwoolls )

**Comment by luke-jr** [comment]
The command for 3.8.0 should work for all versions you'd be testing.

**Comment by DeathfireD** [comment]
@luke-jr Well I'm not having any luck. That white page put a hamper on any testing I had planed to do tonight lol. I'll try again tomorrow.
