### ISSUE TITLE
Gridseed driver gives WTF MUTEX ERROR ON UNLOCK! in bfgminer-4.99.1-58-gcaa3aad

### ISSUE THREAD

**Issue by minusbat** [luke-jr/bfgminer#587]
I am happily running a single gridseed orb using bfgminer-4.9.0-20-gadc766b, and was tryying out the latest pull from git with it. This gives me the error above when trying to initialise the miner however.

I am running under FreeBSD, and only enabling the gridseed driver when I configure the package.
Output from bfgminer below:

 [2014-11-24 15:09:24] Runtime: 0 hrs : 1 mins : 55 secs
 [2014-11-24 15:09:24] Average hashrate: 0.0 Megahash/s
 [2014-11-24 15:09:24] Solved blocks: 0
 [2014-11-24 15:09:24] Best share difficulty: 0
 [2014-11-24 15:09:24] Share submissions: 0
 [2014-11-24 15:09:24] Accepted shares: 0
 [2014-11-24 15:09:24] Rejected shares: 0 + 0 stale (nan%)
 [2014-11-24 15:09:24] Accepted difficulty shares: 0
 [2014-11-24 15:09:24] Rejected difficulty shares: 0
 [2014-11-24 15:09:24] Hardware errors: 0
 [2014-11-24 15:09:24] Network transfer:   3.2 /   0.4 kB  ( 28.3 /   3.2  B/s)
 [2014-11-24 15:09:24] Efficiency (accepted shares \* difficulty / 2 KB): 0.00
 [2014-11-24 15:09:24] Utility (accepted shares / min): 0.00/min

 [2014-11-24 15:09:24] Unable to get work from server occasions: 0
 [2014-11-24 15:09:24] Work items generated locally: 27
 [2014-11-24 15:09:24] Submitting work remotely delay occasions: 0
 [2014-11-24 15:09:24] New blocks detected on network: 3

 [2014-11-24 15:09:24] Summary of per device statistics:

 [2014-11-24 15:09:24] GSD0 Initializing...
 [2014-11-24 15:09:24] GSD0a Initializing...
 [2014-11-24 15:09:24] GSD0b Initializing...
 [2014-11-24 15:09:24] GSD0c Initializing...
 [2014-11-24 15:09:24] GSD0d Initializing...
 [2014-11-24 15:09:24] GSD0e Initializing...
 [2014-11-24 15:09:24]
WTF MUTEX ERROR ON UNLOCK!

**Comment by luke-jr** [comment]
Can you set a breakpoint on miner.h line 801 (with the error message) and get a backtrace of this?

**Comment by minusbat** [comment]
> Can you set a breakpoint on miner.h line 801 (with the error message) and get a backtrace of this?

Yes, I should be able to - I can also print out the errno result at
that ppoint, as I thing it gets set when that call fails.

By the way, I have also verified tthat the same error happens when
doing CPU mining only (and with only that driver enabled), which should
make it easier to track down, and means it is independent of the
gridseed hardware.

**Comment by minusbat** [comment]
> Can you set a breakpoint on miner.h line 801 (with the error message) and get a backtrace of this?

Here is the backtrace. I did it using abort() instead of
a breakpoint, so I have the coredump to look at, hence the
first 3 bis of the trace. Errno at this point is 2 which
is "No such file or directory".

---

Core was generated by `bfgminer'.
Program terminated with signal SIGABRT, Aborted.
#0  0x0000000801c1fdcc in thr_kill () from /lib/libc.so.7
(gdb) bt
#0  0x0000000801c1fdcc in thr_kill () from /lib/libc.so.7
#1  0x0000000801cc66fb in abort () from /lib/libc.so.7
#2  0x0000000000406c2f in mutex_unlock_noyield (lock=0x803c3ef30) at ./miner.h:801
#3  0x0000000000406c49 in mutex_unlock (lock=0x803c3ef30) at ./miner.h:807
#4  0x00000000004397d2 in main (argc=1, argv=0x7fffffffe5f8) at miner.c:13682

**Comment by luke-jr** [comment]
Fixed in e012c91, thanks for the report. Please close when confirmed fixed.

**Comment by minusbat** [comment]
Yes, it no longer crashes with that fix. Thanks.
